/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {Translation} from '@ngneat/transloco';

export const ARA: Translation = {
  'Drop your slides here': 'Drop your slides here',
  'Drop your fields here': 'Drop your fields here',
  'Drop your file here or click to select': 'Drop your file here or click to select',
  'Delete': 'Delete',
  'Upload image': 'Upload image',
  'Camera': 'Camera',
  'Save': 'Save',
  'Errors': 'Errors',
  'Drop image': 'Drop image',
  'Drop your image here!': 'Drop your image here!',
  'Edit choices origin': 'Edit choices origin',
  'Close': 'Close',
  'Name': 'Name',
  'Label': 'Label',
  'Add value': 'Add value',
  'Value': 'Value',
  'delete': 'delete',
  'Edit condition': 'Edit condition',
  'Choices': 'Choices',
  'Identifier': 'Identifier',
  'Default columns': 'Default columns',
  'Select the fields that will be shown as columns in the form list page':
    'Select the fields that will be shown as columns in the form list page',
  'New..': 'New..',
  'Properties': 'Properties',
  'Visibility': 'Visibility',
  'Visible': 'Visible',
  'Always': 'Always',
  'Never': 'Never',
  'Condition...': 'Condition...',
  'Branches': 'Branches',
  'Repetitions': 'Repetitions',
  'Max repetitions': 'Max repetitions',
  'Field size': 'Field size',
  'Size': 'Size',
  'Hint': 'Hint',
  'Description': 'Description',
  'Default value': 'Default value',
  'Formula': 'Formula',
  'Not empty': 'Not empty',
  'Min value': 'Min value',
  'Max value': 'Max value',
  'Min digits': 'Min digits',
  'Max digits': 'Max digits',
  'Validation': 'Validation',
  'No conditions': 'No conditions',
  'Not empty warning': 'Not empty warning',
  'Warnings': 'Warnings',
  'No warnings': 'No warnings',
  'Go to next slide condition': 'Go to next slide condition',
  'Choices origins': 'Choices origins',
  'Choices filter': 'Choices filter',
  'Force expanded selection': 'Force expanded selection',
  'Force narrow selection': 'Force narrow selection',
  'Trigger selection': 'Trigger selection',
  'No trigger condition': 'No trigger condition',
  'Edit identifier': 'Edit identifier',
  'Show': 'Show',
  'All': 'All',
  'First': 'First',
  'Last': 'Last',
  'Error message': 'Error message',
  'Warning message': 'Warning message',
  'Invalid condition! Please check syntax.': 'Invalid condition! Please check syntax.',
  'Drop here': 'Drop here',
  'Main Data': 'Main Data',
  'Edit': 'Edit',
  'Remove': 'Remove',
  'add dataset': 'add dataset',
  'add data': 'add data',
  'Add Main Data': 'Add Main Data',
  'data': 'data',
  'CSS style': 'CSS style',
  'height': 'height',
  'margin': 'margin',
  'border': 'border',
  'padding': 'padding',
  'content': 'content',
  'margin top': 'margin top',
  'margin right': 'margin right',
  'margin bottom': 'margin bottom',
  'margin left': 'margin left',
  'padding top': 'padding top',
  'padding right': 'padding right',
  'padding bottom': 'padding bottom',
  'padding left': 'padding left',
  'border width': 'border width',
  'border width top': 'border width top',
  'border width right': 'border width right',
  'border width bottom': 'border width bottom',
  'border width left': 'border width left',
  'border radius': 'border radius',
  'border radius top left': 'border radius top left',
  'border radius top right': 'border radius top right',
  'border radius bottom left': 'border radius bottom left',
  'border radius bottom right': 'border radius bottom right',
  'font size': 'font size',
  'Font size': 'Font size',
  'Font style': 'Font style',
  'Normal': 'Normal',
  'Italic': 'Italic',
  'Oblique': 'Oblique',
  'Align': 'Align',
  'Center': 'Center',
  'Left': 'Left',
  'Right': 'Right',
  'properties of': 'properties of',
  'Column': 'Column',
  'Add column': 'Add column',
  'paste a link': 'paste a link',
  'Set image': 'Set image',
  'Choose type of Chart': 'Choose type of Chart',
  'Labels': 'Labels',
  'Border width': 'Border width',
  'Hide empty rows': 'Hide empty rows',
  'Table definition': 'Table definition',
  'No value selected': 'لم يتم تحديد أي قيمة',
  'Clear': 'مسح',
  'OK': 'موافق',
  'Appearance': 'المظهر',
  'Default': 'افتراضي',
  'Rating': 'التقييم',
  'Start': 'البداية',
  'End': 'النهاية',
  'Step': 'الخطوة',
  'Readonly': 'للقراءة فقط',
  'HTML': 'HTML',
  'Image': 'صورة',
  'Latitude': 'خط العرض',
  'Longitude': 'خط الطول',
  'Search': 'بحث',
  'Search elements...': 'البحث عن العناصر...',
  'Nothing found': 'لا توجد نتائج',
  'Items per page:': 'العناصر في الصفحة:',
  'Name is required': 'الاسم مطلوب',
  'Name already exists': 'الاسم موجود بالفعل',
  'Download as XLSForm': 'تنزيل كملف XLSForm',
  'Drop your image here or click to select': 'أفلت صورتك هنا أو انقر للتحديد',
  'Structure': 'البنية',
  'Text': 'نص',
  'Numeric': 'رقمي',
  'Choice fields': 'الخيارات',
  'Date & time': 'التاريخ والوقت',
  'Advanced': 'متقدم',
  'text': 'text',
  'formatted text': 'formatted text',
  'number': 'number',
  'yes/no': 'yes/no',
  'single choice': 'single choice',
  'choice with search': 'choice with search',
  'multiple choice': 'multiple choice',
  'multiple choice with search': 'multiple choice with search',
  'calculated': 'calculated',
  'note': 'note',
  'date': 'date',
  'date range': 'date range',
  'time': 'time',
  'table': 'table',
  'position': 'position',
  'barcode': 'barcode',
  'attachment': 'attachment',
  'image': 'image',
  'video': 'video',
  'range': 'range',
  'rating': 'rating',
  'signature': 'signature',
  'audio': 'audio',
  'field': 'field',
  'characters': 'characters',
  '{{fields}} fields in {{slides}} slides need attention': '{{fields}} fields in {{slides}} slides need attention',
  'Add': 'Add',
  'Approve signature': 'Approve signature',
  'Back': 'Back',
  'Delete Audio': 'Delete audio',
  'Forward': 'Forward',
  'Go to slide': 'Go to slide',
  'Lat': 'Lat',
  'Lng': 'Lng',
  'Locate': 'Locate',
  'Number of': 'Number of',
  'Record': 'Record',
  'Replace': 'Replace',
  'Scan': 'Scan',
  'Sign here to continue': 'Sign here to continue',
  'Start Recording': 'Start recording',
  'Stop Recording': 'Stop recording',
  'empty': 'empty',
  'of': 'of',
  'recorded': 'recorded',
  'recording': 'recording',
  'repetitions': 'repetitions',
  'slide': 'slide',
};
