/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {Translation} from '@ngneat/transloco';

export const ETH: Translation = {
  'Drop your slides here': 'ተንሸራታቾችዎን እዚህ ይጥሉ',
  'Drop your file here or click to select': 'ፋይልዎን እዚህ ጣል ያድርጉ ወይም አጠቃላይ ጠቅ ያድርጉ',
  'Delete': 'ሰርዝ',
  'Upload image': 'ስቀልን ምስል',
  'Camera': 'ካሜራ',
  'Save': 'አስቀምጥ',
  'Errors': 'ስህተቶች',
  'Drop image': 'ምስል ጣል',
  'Drop your image here!': 'ምስልዎን እዚህ ጣል ያድርጉ!',
  'Edit choices origin': 'ምርጫዎችን አመጣጥ ያርትዑ',
  'Close': 'ዝጋ',
  'Name': 'ሰርዝ0',
  'Label': 'ሰርዝ1',
  'Add value': 'ሰርዝ2',
  'Value': 'ሰርዝ3',
  'delete': 'ሰርዝ4',
  'Edit condition': 'ሰርዝ5',
  'Choices': 'ሰርዝ6',
  'Identifier': 'ሰርዝ7',
  'Default columns': 'Default columns',
  'Select the fields that will be shown as columns in the form list page':
    'Select the fields that will be shown as columns in the form list page',
  'New..': 'ሰርዝ8',
  'Properties': 'ሰርዝ9',
  'Visibility': 'ስቀልን ምስል0',
  'Visible': 'ስቀልን ምስል1',
  'Always': 'ስቀልን ምስል2',
  'Never': 'ስቀልን ምስል3',
  'Condition...': 'ስቀልን ምስል4',
  'Branches': 'ስቀልን ምስል5',
  'Repetitions': 'ስቀልን ምስል6',
  'Min repetitions': 'ስቀልን ምስል7',
  'Max repetitions': 'ስቀልን ምስል8',
  'Field size': 'ስቀልን ምስል9',
  'Size': 'ካሜራ0',
  'Hint': 'ካሜራ1',
  'Description': 'ካሜራ2',
  'Default value': 'ካሜራ3',
  'Formula': 'ካሜራ4',
  'Not empty': 'ካሜራ5',
  'Min value': 'ካሜራ6',
  'Max value': 'ካሜራ7',
  'Min digits': 'ካሜራ8',
  'Max digits': 'ካሜራ9',
  'Validation': 'አስቀምጥ0',
  'No conditions': 'አስቀምጥ1',
  'Not empty warning': 'አስቀምጥ2',
  'Warnings': 'አስቀምጥ3',
  'No warnings': 'አስቀምጥ4',
  'Go to next slide condition': 'አስቀምጥ5',
  'Choices origins': 'አስቀምጥ6',
  'Choices filter': 'አስቀምጥ7',
  'Force expanded selection': 'አስቀምጥ8',
  'Force narrow selection': 'አስቀምጥ9',
  'Trigger selection': 'ርጫን የሚያነቃቃ',
  'No trigger condition': 'የማስነሻ ሁኔታ የለም',
  'Edit identifier': 'መለያ አርትዕ',
  'Show': 'አሳይ',
  'All': 'ሁሉም',
  'First': 'የመጀመሪያ',
  'Last': 'የመጨረሻ',
  'Error message': 'የስህተት መልእክት',
  'Warning message': 'የማስጠንቀቂያ መልእክት',
  'Invalid condition! Please check syntax.': 'ልክ ያልሆነ ሁኔታ! እባክዎ አገባብ ይፈትሹ።',
  'Drop here': 'የማስነሻ ሁኔታ የለም0',
  'Main Data': 'የማስነሻ ሁኔታ የለም1',
  'Edit': 'የማስነሻ ሁኔታ የለም2',
  'Remove': 'የማስነሻ ሁኔታ የለም3',
  'add dataset': 'የማስነሻ ሁኔታ የለም4',
  'add data': 'የማስነሻ ሁኔታ የለም5',
  'Add Main Data': 'የማስነሻ ሁኔታ የለም6',
  'data': 'የማስነሻ ሁኔታ የለም7',
  'CSS style': 'የማስነሻ ሁኔታ የለም8',
  'height': 'የማስነሻ ሁኔታ የለም9',
  'margin': 'መለያ አርትዕ0',
  'border': 'መለያ አርትዕ1',
  'padding': 'መለያ አርትዕ2',
  'content': 'መለያ አርትዕ3',
  'margin top': 'መለያ አርትዕ4',
  'margin right': 'መለያ አርትዕ5',
  'margin bottom': 'መለያ አርትዕ6',
  'margin left': 'መለያ አርትዕ7',
  'padding top': 'መለያ አርትዕ8',
  'padding right': 'መለያ አርትዕ9',
  'padding bottom': 'አሳይ0',
  'padding left': 'አሳይ1',
  'border width': 'አሳይ2',
  'border width top': 'አሳይ3',
  'border width right': 'አሳይ4',
  'border width bottom': 'አሳይ5',
  'border width left': 'አሳይ6',
  'border radius': 'አሳይ7',
  'border radius top left': 'አሳይ8',
  'border radius top right': 'አሳይ9',
  'border radius bottom left': 'ሁሉም0',
  'border radius bottom right': 'ሁሉም1',
  'font size': 'ሁሉም2',
  'Font size': 'ሁሉም3',
  'Font style': 'ሁሉም4',
  'Normal': 'ሁሉም5',
  'Italic': 'ሁሉም6',
  'Oblique': 'ሁሉም7',
  'Align': 'ሁሉም8',
  'Center': 'ሁሉም9',
  'Left': 'የመጀመሪያ0',
  'Right': 'የመጀመሪያ1',
  'properties of': 'የመጀመሪያ2',
  'Column': 'የመጀመሪያ3',
  'Add column': 'የመጀመሪያ4',
  'paste a link': 'የመጀመሪያ5',
  'Set image': 'የመጀመሪያ6',
  'Choose type of Chart': 'የመጀመሪያ7',
  'Labels': 'የመጀመሪያ8',
  'Border width': 'የመጀመሪያ9',
  'Hide empty rows': 'ባዶ ረድፎችን ደብቅ',
  'Table definition': 'የሠንጠረዥ ትርጉም',
  'No value selected': 'ምንም እሴት አልተመረጠም',
  'Clear': 'አጽዳ',
  'OK': 'እሺ',
  'Appearance': 'መልክ',
  'Default': 'ነባሪ',
  'Rating': 'ደረጃ አሰጣጥ',
  'Start': 'መጀመሪያ',
  'End': 'መጨረሻ',
  'Step': 'እርምጃ',
  'Readonly': 'ለማንበብ ብቻ',
  'HTML': 'HTML',
  'Image': 'ምስል',
  'Latitude': 'ኬክሮስ',
  'Longitude': 'ኬንትሮስ',
  'Search': 'ፍለጋ',
  'Search elements...': 'ንጥሎችን ፈልግ...',
  'Nothing found': 'ምንም አልተገኘም',
  'Items per page:': 'በአንድ ገጽ ንጥሎች፡',
  'Name is required': 'ስም ያስፈልጋል',
  'Name already exists': 'ስሙ አስቀድሞ አለ',
  'Download as XLSForm': 'እንደ XLSForm አውርድ',
  'Drop your image here or click to select': 'ምስልዎን እዚህ ይጣሉ ወይም ለመምረጥ ጠቅ ያድርጉ',
  'Structure': 'አወቃቀር',
  'Text': 'ጽሑፍ',
  'Numeric': 'ቁጥር',
  'Choice fields': 'ምርጫዎች',
  'Date & time': 'ቀን እና ሰዓት',
  'Advanced': 'የላቀ',
  'text': 'ጽሑፍ',
  'formatted text': 'የተቀረጸ ጽሑፍ',
  'number': 'ቁጥር',
  'yes/no': 'አዎ/አይ',
  'single choice': 'ነጠላ ምርጫ',
  'choice with search': 'በፍለጋ ምርጫ',
  'multiple choice': 'ብዙ ምርጫ',
  'multiple choice with search': 'በፍለጋ ብዙ ምርጫ',
  'calculated': 'የተሰላ',
  'note': 'ማስታወሻ',
  'date': 'ቀን',
  'date range': 'የቀን ክልል',
  'time': 'ሰዓት',
  'table': 'ሰንጠረዥ',
  'position': 'ቦታ',
  'barcode': 'የባር ኮድ',
  'attachment': 'አባሪ',
  'image': 'ምስል',
  'video': 'ቪዲዮ',
  'range': 'ክልል',
  'rating': 'ደረጃ',
  'signature': 'ፊርማ',
  'audio': 'ድምፅ',
  'field': 'መስክ',
  'characters': 'ቁምፊዎች',
  '{{fields}} fields in {{slides}} slides need attention': '{{fields}} መስኮች በ{{slides}} ስላይዶች ውስጥ ትኩረት ይሻሉ',
  'Add': 'ጨምር',
  'Approve signature': 'ፊርማ አጽድቅ',
  'Back': 'ተመለስ',
  'Delete Audio': 'ድምፅ ሰርዝ',
  'Forward': 'ወደፊት',
  'Go to slide': 'ወደ ስላይድ ሂድ',
  'Lat': 'Lat',
  'Lng': 'Lng',
  'Locate': 'አካባቢ ፈልግ',
  'Number of': 'ቁጥር የ',
  'Record': 'ቅረጽ',
  'Replace': 'ተካ',
  'Scan': 'ቅኝት',
  'Sign here to continue': 'ለመቀጠል እዚህ ይፈርሙ',
  'Start Recording': 'ቀረጻ ጀምር',
  'Stop Recording': 'ቀረጻ አቁም',
  'empty': 'ባዶ',
  'of': 'ከ',
  'recorded': 'ተቀርጿል',
  'recording': 'በመቅረጽ ላይ',
  'repetitions': 'ድግግሞሽ',
  'slide': 'ስላይድ',
};
