/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {Translation} from '@ngneat/transloco';

export const PRT: Translation = {
  'Drop your slides here': 'Solte seus slides aqui',
  'Drop your fields here': 'Solte seus campos aqui',
  'Drop your file here or click to select': 'Solte seu arquivo aqui ou clique para selecionar',
  'Delete': 'Excluir',
  'Upload image': 'Enviar Imagem',
  'Camera': 'Câmera',
  'Save': 'Gravar',
  'Errors': 'Erros',
  'Drop image': 'Soltar imagem',
  'Drop your image here!': 'Drop your image here!Solte sua imagem aqui!',
  'Edit choices origin': 'Editar a origem das escolhas',
  'Close': 'Perto',
  'Name': 'Nome',
  'Label': 'a etiqueta',
  'Add value': 'adicionar valores',
  'Value': 'Valor',
  'delete': 'excluir',
  'Edit condition': 'Modificar a condicao',
  'Choices': 'Escolha',
  'Identifier': 'Identificador',
  'Default columns': 'Colunas padrão',
  'Select the fields that will be shown as columns in the form list page':
    'Selecione os campos que serão exibidos como colunas na página de lista de formulários',
  'New..': 'Novo..',
  'Properties': 'Propriedades',
  'Visibility': 'Visibilidade',
  'Visible': 'Visível',
  'Always': 'Sempre',
  'Never': 'Nunca',
  'Condition...': 'Doença...',
  'Branches': 'Departamentos',
  'Repetitions': 'Repetições',
  'Max repetitions': 'Repetições máximas',
  'Field size': 'Tamanho do Campos',
  'Size': 'Tamanho',
  'Hint': 'sugestão',
  'Description': 'Descricao',
  'Default value': 'Valor padrao',
  'Formula': 'Formula',
  'Not empty': 'Não está vazio',
  'Min value': 'Valor mínimo',
  'Max value': 'Valor máximo',
  'Min digits': 'Dígitos mínimos',
  'Max digits': 'Dígitos máximos',
  'Validation': 'Validação',
  'No conditions': 'Sem condições',
  'Not empty warning': 'Aviso de não vazio',
  'Warnings': 'Avisos',
  'No warnings': 'Sem avisos',
  'Go to next slide condition': 'Vá para a próxima condição de slide',
  'Choices origins': 'Origens de escolhas',
  'Choices filter': 'Filtro de opções',
  'Force expanded selection': 'Force expanded selection',
  'Force narrow selection': 'Forçar seleção expandida',
  'Trigger selection': 'Seleção de gatilho',
  'No trigger condition': 'Sem condição de gatilho',
  'Edit identifier': 'Editar identificador',
  'Show': 'Mostrar',
  'All': 'Tudo',
  'First': 'Primeiro',
  'Last': 'Durar',
  'Error message': 'Mensagem de erro',
  'Warning message': 'Mensagem de aviso',
  'Invalid condition! Please check syntax.': 'Condição inválida! Verifique a sintaxe.',
  'Drop here': 'Solta aqui',
  'Main Data': ' Dados principais',
  'Edit': 'Editar',
  'Remove': 'Remover',
  'add dataset': 'add dataset',
  'add data': 'adicionar dados',
  'Add Main Data': 'adicionar dados principais',
  'data': 'dados',
  'CSS style': 'CSS style',
  'height': 'height',
  'margin': 'margin',
  'border': 'border',
  'padding': 'padding',
  'content': 'content',
  'margin top': 'margin top',
  'margin right': 'margin right',
  'margin bottom': 'margin bottom',
  'margin left': 'margin left',
  'padding top': 'padding top',
  'padding right': 'padding right',
  'padding bottom': 'padding bottom',
  'padding left': 'padding left',
  'border width': 'border width',
  'border width top': 'border width top',
  'border width right': 'border width right',
  'border width bottom': 'border width bottom',
  'border width left': 'border width left',
  'border radius': 'border radius',
  'border radius top left': 'border radius top left',
  'border radius top right': 'border radius top right',
  'border radius bottom left': 'border radius bottom left',
  'border radius bottom right': 'border radius bottom right',
  'font size': 'font size',
  'Font size': 'Font size',
  'Font style': 'Font style',
  'Normal': 'Normal',
  'Italic': 'Italic',
  'Oblique': 'Oblique',
  'Align': 'Align',
  'Center': 'Center',
  'Left': 'Left',
  'Right': 'Right',
  'properties of': 'propriedades de',
  'Column': 'Coluna',
  'Add column': 'Adicionar coluna',
  'paste a link': 'cole um link',
  'Set image': 'Definir imagem',
  'Choose type of Chart': 'Escolha o tipo de gráfico',
  'Labels': 'Etiquetas',
  'Border width': 'Border width',
  'Hide empty rows': 'Ocultar linhas vazias',
  'Table definition': 'Definição da tabela',
  'Please sign here': 'Por favor, assine aqui',
  'No value selected': 'Nenhum valor selecionado',
  'Clear': 'Limpar',
  'OK': 'OK',
  'Appearance': 'Aparência',
  'Default': 'Padrão',
  'Rating': 'Avaliação',
  'Start': 'Início',
  'End': 'Fim',
  'Step': 'Passo',
  'Readonly': 'Somente leitura',
  'HTML': 'HTML',
  'Image': 'Imagem',
  'Latitude': 'Latitude',
  'Longitude': 'Longitude',
  'Search': 'Pesquisar',
  'Search elements...': 'Pesquisar elementos...',
  'Nothing found': 'Nada encontrado',
  'Items per page:': 'Itens por página:',
  'Name is required': 'O nome é obrigatório',
  'Name already exists': 'O nome já existe',
  'Download as XLSForm': 'Baixar como XLSForm',
  'Drop your image here or click to select': 'Solte sua imagem aqui ou clique para selecionar',
  'Structure': 'Estrutura',
  'Text': 'Texto',
  'Numeric': 'Numéricos',
  'Choice fields': 'Escolhas',
  'Date & time': 'Data e hora',
  'Advanced': 'Avançados',
  'text': 'texto',
  'formatted text': 'texto formatado',
  'number': 'número',
  'yes/no': 'sim/não',
  'single choice': 'escolha única',
  'choice with search': 'escolha com pesquisa',
  'multiple choice': 'escolha múltipla',
  'multiple choice with search': 'escolha múltipla com pesquisa',
  'calculated': 'calculado',
  'note': 'nota',
  'date': 'data',
  'date range': 'intervalo de datas',
  'time': 'hora',
  'table': 'tabela',
  'position': 'posição',
  'barcode': 'código de barras',
  'attachment': 'anexo',
  'image': 'imagem',
  'video': 'vídeo',
  'range': 'intervalo',
  'rating': 'avaliação',
  'signature': 'assinatura',
  'audio': 'áudio',
  'field': 'campo',
  'characters': 'caracteres',
  '{{fields}} fields in {{slides}} slides need attention': '{{fields}} campos em {{slides}} slides precisam de atenção',
  'Add': 'Adicionar',
  'Approve signature': 'Aprovar assinatura',
  'Back': 'Voltar',
  'Delete Audio': 'Excluir áudio',
  'Forward': 'Avançar',
  'Go to slide': 'Ir para o slide',
  'Lat': 'Lat',
  'Lng': 'Lng',
  'Locate': 'Localizar',
  'Number of': 'Número de',
  'Record': 'Gravar',
  'Replace': 'Substituir',
  'Scan': 'Digitalizar',
  'Sign here to continue': 'Assine aqui para continuar',
  'Start Recording': 'Iniciar gravação',
  'Stop Recording': 'Parar gravação',
  'empty': 'vazio',
  'of': 'de',
  'recorded': 'gravado',
  'recording': 'gravando',
  'repetitions': 'repetições',
  'slide': 'slide',
};
