pipeline {
  environment {
    scmInfo = checkout scm
    gitBranch = scmInfo.GIT_BRANCH.replace("origin/", "")
  }
  stages {
    stage('Setup') {
      steps {
        sh 'yarn install --frozen-lockfile --non-interactive'
      }
    }
    stage('Lint') {
      steps {
        sh 'yarn -s lint'
      }
    }
    stage('Build') {
      steps {
        sh './scripts/build.mjs'
      }
    }
    stage('Unit tests') {
      steps {
        sh 'yarn -s test:ci'
      }
    }
    stage('E2E tests') {
      steps {
        sh './scripts/e2e-ci.mjs'
      }
    }
    stage('Build release') {
      steps {
        sh './scripts/release.mjs'
      }
    }
    stage('Publish snapshots') {
      when {
        expression {
          return gitBranch == 'master'
        }
      }
      steps {
        sh './scripts/build-docs.mjs'
        sh './scripts/jenkins/publish-snapshots.sh'
        sh 'node ./scripts/deploy-dev-app.js'
      }
    }
    stage('Publish') {
      steps {
        sh './scripts/publish.mjs'
      }
    }
  }
}
