pipeline {
  agent {
    label 'bazel-build-28'
  }
  environment {
    scmInfo = checkout scm
    gitBranch = scmInfo.GIT_BRANCH.replace("origin/", "")
    cacheParams = getCacheParams()
  }
  stages {
    stage('Get cache') {
      steps {
        getCache(cacheParams)
      }
    }
    stage('Setup') {
      steps {
        restoreCache(cacheParams)
        sh 'cat .jenkins/bazelrc >> .bazelrc'
        sh 'yarn install --frozen-lockfile --non-interactive'
        sh './scripts/circleci/setup_bazel_binary.sh'
      }
    }
    stage('Lint') {
      steps {
        sh 'yarn -s bazel build //:rollup_globals'
        sh 'yarn -s check-rollup-globals $(yarn -s bazel info bazel-bin)/rollup_globals.json'
        sh 'yarn -s bazel build //:entry_points_manifest'
        sh 'yarn check-entry-point-setup $(yarn -s bazel info bazel-bin)/entry_points_manifest.json'
        sh 'yarn -s lint'
        sh 'yarn -s ts-circular-deps:check'
      }
    }
    stage('Build') {
      steps {
        sh 'yarn -s bazel build src/... --build_tag_filters=-docs-package,-release-package'
      }
    }
    stage('Unit tests') {
      steps {
        sh 'yarn -s bazel test src/... --build_tag_filters=-docs-package,-e2e --test_tag_filters=-e2e --config=view-engine --build_tests_only'
        sh 'yarn -s bazel test src/... --build_tag_filters=-e2e --test_tag_filters=-e2e --build_tests_only'
      }
    }
    stage('API guard tests') {
      steps {
        sh 'yarn -s bazel test tools/public_api_guard/...'
      }
    }
    stage('JSON schema guard tests') {
      steps {
        sh 'yarn -s bazel test tools/schemas_guard/...'
      }
    }
    stage('Integration tests') {
      steps {
        sh 'yarn -s bazel test src/... --build_tag_filters=e2e --test_tag_filters=e2e --build_tests_only'
      }
    }
    stage('Release output') {
      steps {
        sh 'yarn build'
        sh 'yarn check-release-output'
        sh 'cp -R dist/releases/* node_modules/@ajf/'
        sh 'rm -f node_modules/__ngcc_entry_points__.json'
        sh 'yarn ngcc --error-on-failed-entry-point --no-tsconfig'
        sh 'rm -Rf node_modules/@ajf/calendars node_modules/@ajf/core node_modules/@ajf/ionic node_modules/@ajf/material'
      }
    }
    stage('Save cache') {
      steps {
        saveCache(cacheParams)
      }
    }
    stage('Publish snapshots') {
      when {
        expression {
          return gitBranch == 'master'
        }
      }
      steps {
        sh 'yarn -s bazel build src/ajf-examples:npm_package --config=release'
        sh './scripts/circleci/publish-snapshots.sh'
        sh 'node ./scripts/deploy-dev-app.js'
      }
    }
  }
}

void getCache(cacheParams) {
  if (cacheParams["hasNodeModulesCache"]) {
    sh "gsutil cp gs://ajf-bazel-remote-cache/${cacheParams["nodeModulesCache"]} ."
  }
  if (cacheParams["hasBazeliskCache"]) {
    sh "gsutil cp gs://ajf-bazel-remote-cache/${cacheParams["hasBazeliskCache"]} ."
  }
  if (cacheParams["hasBazelRepositoryCache"]) {
    sh "gsutil cp gs://ajf-bazel-remote-cache/${cacheParams["bazelRepositoryCache"]} ."
  }
}

void restoreCache(cacheParams) {
  sh "rm -Rf node_modules ~/.cache/bazelisk ~/bazel_repository_cache"
  if (cacheParams["hasNodeModulesCache"]) {
    sh "tar xfz ${cacheParams["nodeModulesCache"]}"
  }
  if (cacheParams["hasBazeliskCache"]) {
    sh "mkdir -p /home/jenkins/.cache"
    sh "tar xfz ${cacheParams["bazeliskCache"]} -C /home/jenkins/.cache"
  }
  if (cacheParams["hasBazelRepositoryCache"]) {
    sh "tar xfz ${cacheParams["bazelRepositoryCache"]} -C /home/jenkins"
  }
}

void saveCache(cacheParams) {
  if (!cacheParams["hasNodeModulesCache"]) {
    sh "tar cfz ${cacheParams["nodeModulesCache"]} node_modules"
    sh "gsutil cp ${cacheParams["nodeModulesCache"]} gs://ajf-bazel-remote-cache/"
  }
  if (!cacheParams["hasBazeliskCache"]) {
    sh "tar cfz ${cacheParams["bazeliskCache"]} -C /home/jenkins/.cache bazelisk"
    sh "gsutil cp ${cacheParams["bazeliskCache"]} gs://ajf-bazel-remote-cache/"
  }
  if (!cacheParams["hasBazelRepositoryCache"]) {
    sh "tar cfz ${cacheParams["bazelRepositoryCache"]} -C /home/jenkins bazel_repository_cache"
    sh "gsutil cp ${cacheParams["bazelRepositoryCache"]} gs://ajf-bazel-remote-cache/"
  }
}

Map getCacheParams() {
  cacheKey = sh(script: "./scripts/jenkins/cache-key.sh", returnStdout: true).trim()
  nodeModulesCache = "ajf-node-modules-${cacheKey}.tar.gz"
  bazeliskCache = "ajf-bazelisk-${cacheKey}.tar.gz"
  bazelRepositoryCache = "ajf-bazel-repository-${cacheKey}.tar.gz"
  try {
    sh "gsutil stat gs://ajf-bazel-remote-cache/${nodeModulesCache}"
    hasNodeModulesCache = true
  } catch (e) {
    hasNodeModulesCache = false
  }
  try {
    sh "gsutil stat gs://ajf-bazel-remote-cache/${bazeliskCache}"
    hasBazeliskCache = true
  } catch (e) {
    hasBazeliskCache = false
  }
  try {
    sh "gsutil stat gs://ajf-bazel-remote-cache/${bazelRepositoryCache}"
    hasBazelRepositoryCache = true
  } catch (e) {
    hasBazelRepositoryCache = false
  }
  return [
    "hasNodeModulesCache": hasNodeModulesCache,
    "hasBazeliskCache": hasBazeliskCache,
    "hasBazelRepositoryCache": hasBazelRepositoryCache,
    "nodeModulesCache": nodeModulesCache,
    "bazeliskCache": bazeliskCache,
    "bazelRepositoryCache": bazelRepositoryCache
  ]
}
