import {CommitMessageConfig} from '@angular/dev-infra-private/commit-message/config';

/**
 * The configuration for `ng-dev commit-message` commands.
 */
export const commitMessage: CommitMessageConfig = {
  maxLineLength: 120,
  minBodyLength: 0,
  minBodyLengthTypeExcludes: ['docs'],
  scopes: [
    'core/barcode',
    'core/calendar',
    'core/chart',
    'core/checkbox-group',
    'core/common',
    'core/file-input',
    'core/forms',
    'core/image',
    'core/map',
    'core/models',
    'core/node-icon',
    'core/page-break',
    'core/page-slider',
    'core/reports',
    'core/table',
    'core/testing',
    'core/text',
    'core/time',
    'core/utils',
    'ionic/barcode',
    'ionic/calendar',
    'ionic/checkbox-group',
    'ionic/forms',
    'ionic/image',
    'ionic/node-icon',
    'ionic/page-slider',
    'ionic/reports',
    'ionic/time',
    'material/barcode',
    'material/calendar',
    'material/checkbox-group',
    'material/form-builder',
    'material/forms',
    'material/image',
    'material/monaco-editor',
    'material/node-icon',
    'material/page-slider',
    'material/reports',
    'material/time',
  ],
};
