/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */


import {Translation} from '@ngneat/transloco';

export const ENG: Translation = {
  'Drop your file here or click to select': 'Drop your file here or click to select',
  'Delete': 'Delete',
  'Upload image': 'Upload image',
  'Camera': 'Camera',
  'Save': 'Save',
  'Errors': 'Errors',
  'Drop image': 'Drop image',
  'Drop your image here!': 'Drop your image here!',
  'Edit choices origin': 'Edit choices origin',
  'Close': 'Close',
  'Name': 'Name',
  'Label': 'Label',
  'Add value': 'Add value',
  'Value': 'Value',
  'delete': 'delete',
  'Edit condition': 'Edit condition',
  'Choices': 'Choices',
  'Identifier': 'Identifier',
  'New..': 'New..',
  'Properties': 'Properties',
  'Visibility': 'Visibility',
  'Visible': 'Visible',
  'Always': 'Always',
  'Never': 'Never',
  'Condition...': 'Condition...',
  'Branches': 'Branches',
  'Repetitions': 'Repetitions',
  'Min repetitions': 'Min repetitions',
  'Max repetitions': 'Max repetitions',
  'Field size': 'Field size',
  'Size': 'Size',
  'Hint': 'Hint',
  'Description': 'Description',
  'Default value': 'Default value',
  'Formula': 'Formula',
  'Not empty': 'Not empty',
  'Min value': 'Min value',
  'Max value': 'Max value',
  'Min digits': 'Min digits',
  'Max digits': 'Max digits',
  'Validation': 'Validation',
  'No conditions': 'No conditions',
  'Not empty warning': 'Not empty warning',
  'Warnings': 'Warnings',
  'No warnings': 'No warnings',
  'Go to next slide condition': 'Go to next slide condition',
  'Choices origins': 'Choices origins',
  'Choices filter': 'Choices filter',
  'Force expanded selection': 'Force expanded selection',
  'Force narrow selection': 'Force narrow selection',
  'Trigger selection': 'Trigger selection',
  'No trigger condition': 'No trigger condition',
  'Edit identifier': 'Edit identifier',
  'Show': 'Show',
  'All': 'All',
  'First': 'First',
  'Last': 'Last',
  'Error message': 'Error message',
  'Warning message': 'Warning message',
  'Invalid condition! Please check syntax.': 'Invalid condition! Please check syntax.',
  'Drop here': 'Drop here',
  'Main Data': 'Main Data',
  'Edit': 'Edit',
  'Remove': 'Remove',
  'add dataset': 'add dataset',
  'add data': 'add data',
  'Add Main Data': 'Add Main Data',
  'data': 'data',
  'CSS style': 'CSS style',
  'height': 'height',
  'margin': 'margin',
  'border': 'border',
  'padding': 'padding',
  'content': 'content',
  'margin top': 'margin top',
  'margin right': 'margin right',
  'margin bottom': 'margin bottom',
  'margin left': 'margin left',
  'padding top': 'padding top',
  'padding right': 'padding right',
  'padding bottom': 'padding bottom',
  'padding left': 'padding left',
  'border width': 'border width',
  'border width top': 'border width top',
  'border width right': 'border width right',
  'border width bottom': 'border width bottom',
  'border width left': 'border width left',
  'border radius': 'border radius',
  'border radius top left': 'border radius top left',
  'border radius top right': 'border radius top right',
  'border radius bottom left': 'border radius bottom left',
  'border radius bottom right': 'border radius bottom right',
  'font size': 'font size',
  'Font size': 'Font size',
  'Font style': 'Font style',
  'Normal': 'Normal',
  'Italic': 'Italic',
  'Oblique': 'Oblique',
  'Align': 'Align',
  'Center': 'Center',
  'Left': 'Left',
  'Right': 'Right',
  'properties of': 'properties of',
  'Column': 'Column',
  'Add column': 'Add column',
  'paste a link': 'paste a link',
  'Set image': 'Set image',
  'Choose type of Chart': 'Choose type of Chart',
  'Labels': 'Labels',
  'Border width': 'Border width'
};
