/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {Translation} from '@ngneat/transloco';

export const ESP: Translation = {
  'Drop your file here or click to select': 'Suelta tu archivo aquí o haz clic para seleccionar',
  'Delete': 'Borrar',
  'Upload image': 'Cargar imagen',
  'Camera': 'Cámara',
  'Save': 'Ahorrar',
  'Errors': 'Errores',
  'Drop image': 'Soltar imagen',
  'Drop your image here!': '¡Suelta tu imagen aquí!',
  'Edit choices origin': 'Editar origen de opciones',
  'Close': 'Cerca',
  'Name': 'Nombre',
  'Label': 'Etiqueta',
  'Add value': 'Añadir valor',
  'Value': 'Valor',
  'delete': 'Eliminar',
  'Edit condition': 'Editar condición',
  'Choices': 'Elecciones',
  'Identifier': 'Identificar',
  'New..': 'Nuevo..',
  'Properties': 'Propiedades',
  'Visibility': 'Visibilidad',
  'Visible': 'Visible',
  'Always': 'Siempre',
  'Never': 'Nunca',
  'Condition...': 'Condición...',
  'Branches': 'Sucursales',
  'Repetitions': 'Repeticiones',
  'Min repetitions': 'Repeticiones mínimas',
  'Max repetitions': 'Repeticiones máximas',
  'Field size': 'Tamaño del campo',
  'Size': 'Tamaño',
  'Hint': 'Insinuación',
  'Description': 'Descripción',
  'Default value': 'Valor por defecto',
  'Formula': 'Fórmula',
  'Not empty': 'No vacío',
  'Min value': 'Valor min',
  'Max value': 'valor máximo',
  'Min digits': 'Dígitos mínimos',
  'Max digits': 'Dígitos máximos',
  'Validation': 'Validación',
  'No conditions': 'Sin condiciones',
  'Not empty warning': 'Advertencia no vacía',
  'Warnings': 'Advertencias',
  'No warnings': 'Sin advertencias',
  'Go to next slide condition': 'Ir a la siguiente condición de diapositiva',
  'Choices origins': 'Orígenes de las elecciones',
  'Choices filter': 'Filtro de opciones',
  'Force expanded selection': 'Forzar selección ampliada',
  'Force narrow selection': 'Forzar selección estrecha',
  'Trigger selection': 'Selección de gatillo',
  'No trigger condition': 'Sin condición de activación',
  'Edit identifier': 'Editar identificador',
  'Show': 'Show',
  'All': 'Todas',
  'First': 'Primero',
  'Last': 'Último',
  'Error message': 'Mensaje de error',
  'Warning message': 'Mensaje de advertencia',
  'Invalid condition! Please check syntax.': '¡Condición inválida! Compruebe la sintaxis.',
  'Drop here': 'Caer aquí',
  'Main Data': 'Datos principales',
  'Edit': 'Editar',
  'Remove': 'Eliminar',
  'add dataset': 'agregar conjunto de datos',
  'add data': 'agregar datos',
  'Add Main Data': 'Agregar datos principales',
  'data': 'datos',
  'CSS style': 'Estilo CSS',
  'height': 'altura',
  'margin': 'margen',
  'border': 'frontera',
  'padding': 'relleno',
  'content': 'contenido',
  'margin top': 'margen superior',
  'margin right': 'margen derecho',
  'margin bottom': 'margen inferior',
  'margin left': 'margen izquierdo',
  'padding top': 'acolchado superior',
  'padding right': 'acolchado a la derecha',
  'padding bottom': 'fondo acolchado',
  'padding left': 'relleno a la izquierda',
  'border width': 'ancho del borde',
  'border width top': 'ancho del borde superior',
  'border width right': 'ancho del borde derecho',
  'border width bottom': 'ancho del borde inferior',
  'border width left': 'ancho del borde a la izquierda',
  'border radius': 'radio de borde',
  'border radius top left': 'radio del borde arriba a la izquierda',
  'border radius top right': 'radio del borde arriba a la derecha',
  'border radius bottom left': 'radio del borde abajo a la izquierda',
  'border radius bottom right': 'radio del borde abajo a la derecha',
  'font size': 'tamaño de fuente',
  'Font size': 'Tamaño de fuente',
  'Font style': 'Estilo de fuente',
  'Normal': 'Normal',
  'Italic': 'Itálico',
  'Oblique': 'Oblicuo',
  'Align': 'Alinear',
  'Center': 'Centrar',
  'Left': 'Izquierda',
  'Right': 'Derecha',
  'properties of': 'propiedades de',
  'Column': 'Columna',
  'Add column': 'Añadir columna',
  'paste a link': 'pegar un enlace',
  'Set image': 'Establecer imagen',
  'Choose type of Chart': 'Elija el tipo de gráfico',
  'Labels': 'Etiquetas',
  'Border width': 'Ancho del borde'
};
