/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Advanced JSON forms (ajf).
 *
 * Advanced JSON forms (ajf) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Advanced JSON forms (ajf) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Advanced JSON forms (ajf).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {Translation} from '@ngneat/transloco';

export const ITA: Translation = {
  'Drop your file here or click to select': 'Trascina qui il tuo file o fai clic per selezionare',
  'Delete': 'Elimina',
  'Upload image': 'Carica immagine',
  'Camera': 'telecamera',
  'Save': 'Salva',
  'Errors': 'Errori',
  'Drop image': 'Rilascia immagine',
  'Drop your image here!': 'Lascia qui la tua immagine!',
  'Edit choices origin': 'Modifica origine scelte',
  'Close': 'Chiudi',
  'Name': 'Nome',
  'Label': 'Etichetta',
  'Add value': 'Aggiungere valore',
  'Value': 'Valore',
  'delete': 'Elimina',
  'Edit condition': 'Modifica condizione',
  'Choices': 'scelte',
  'Identifier': 'Identificatori',
  'New..': 'Nuovo..',
  'Properties': 'Proprietà',
  'Visibility': 'Visibilità',
  'Visible': 'Visibile',
  'Always': 'Sempre',
  'Never': 'Mai',
  'Condition...': 'Condizione...',
  'Branches': 'rami',
  'Repetitions': 'ripetizioni',
  'Min repetitions': 'Ripetizioni minime',
  'Max repetitions': 'Ripetizioni massime',
  'Field size': 'Dimensione del campo',
  'Size': 'Dimensione',
  'Hint': 'Suggerimento',
  'Description': 'Descrizione',
  'Default value': 'Valore predefinito',
  'Formula': 'Formula',
  'Not empty': 'Non vuoto',
  'Min value': 'Valore minimo',
  'Max value': 'Valore massimo',
  'Min digits': 'Cifre minime',
  'Max digits': 'Cifre massime',
  'Validation': 'Convalida',
  'No conditions': 'Nessuna condizione',
  'Not empty warning': 'Avviso non vuoto',
  'Warnings': 'Avvertenze',
  'No warnings': 'Nessun avviso',
  'Go to next slide condition': 'Vai alla condizione della diapositiva successiva',
  'Choices origins': 'Origini delle scelte',
  'Choices filter': 'Filtro scelte',
  'Force expanded selection': 'Forza selezione espansa',
  'Force narrow selection': 'Forza selezione stretta',
  'Trigger selection': 'Selezione trigger',
  'No trigger condition': 'Nessuna condizione di trigger',
  'Edit identifier': 'Modifica identificatore',
  'Show': 'Mostrare',
  'All': 'Tutti',
  'First': 'Primo',
  'Last': 'Scorso',
  'Error message': 'Messaggio di errore',
  'Warning message': 'Messaggio di avviso',
  'Invalid condition! Please check syntax.':
      'Condizione non valida! Si prega di controllare la sintassi.',
  'Drop here': 'Rilascia qui',
  'Main Data': 'Dati principali',
  'Edit': 'modificare',
  'Remove': 'Rimuovere',
  'add dataset': 'aggiungi set di dati',
  'add data': 'aggiungi dati',
  'Add Main Data': 'Aggiungi dati principali',
  'data': 'dati',
  'CSS style': 'Stile CSS',
  'height': 'altezza',
  'margin': 'margine',
  'border': 'confine',
  'padding': 'imbottitura',
  'content': 'soddisfare',
  'margin top': 'margine superiore',
  'margin right': 'margine destro',
  'margin bottom': 'margine inferiore',
  'margin left': 'margine sinistro',
  'padding top': 'padding superiore',
  'padding right': 'padding a destra',
  'padding bottom': 'padding inferiore',
  'padding left': 'padding a sinistra',
  'border width': 'larghezza del bordo',
  'border width top': 'larghezza del bordo in alto',
  'border width right': 'larghezza del bordo a destra',
  'border width bottom': 'larghezza bordo inferiore',
  'border width left': 'larghezza bordo sinistra',
  'border radius': 'raggio di bordo',
  'border radius top left': 'raggio del bordo in alto a sinistra',
  'border radius top right': 'raggio del bordo in alto a destra',
  'border radius bottom left': 'raggio del bordo in basso a sinistra',
  'border radius bottom right': 'raggio del bordo in basso a destra',
  'font size': 'dimensione del font',
  'Font size': 'Dimensione del font',
  'Font style': 'Stile carattere',
  'Normal': 'Normale',
  'Italic': 'Corsivo',
  'Oblique': 'Obliquo',
  'Align': 'Allineare',
  'Center': 'Centro',
  'Left': 'Sinistra',
  'Right': 'Giusto',
  'properties of': 'proprietà di',
  'Column': 'Colonna',
  'Add column': 'Aggiungi colonna',
  'paste a link': 'incolla un link',
  'Set image': 'Imposta immagine',
  'Choose type of Chart': 'Scegli il tipo di grafico',
  'Labels': 'etichette',
  'Border width': 'Larghezza del bordo'
};
